// <auto-generated />
using BasicLinQ.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicLinQ.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BasicLinQ.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "apple",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "banana",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "orange",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "grape",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "mango",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "television",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Name = "laptop",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "keyboard",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Name = "monitor",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Name = "knife",
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Name = "spoon",
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Name = "bowl",
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Name = "chopsticks",
                            SupplierId = 3
                        });
                });

            modelBuilder.Entity("BasicLinQ.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "fruit",
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "electronic",
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "household",
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "misc",
                            SupplierId = 4
                        });
                });

            modelBuilder.Entity("BasicLinQ.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "supplier 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "supplier 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "supplier 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "supplier 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "supplier 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "supplier 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "supplier 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "supplier 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "supplier 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "supplier 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "supplier 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "supplier 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "supplier 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "supplier 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "supplier 15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "supplier 16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "supplier 17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "supplier 18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "supplier 19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "supplier 20"
                        },
                        new
                        {
                            Id = 21,
                            Name = "supplier 21"
                        },
                        new
                        {
                            Id = 22,
                            Name = "supplier 22"
                        },
                        new
                        {
                            Id = 23,
                            Name = "supplier 23"
                        },
                        new
                        {
                            Id = 24,
                            Name = "supplier 24"
                        },
                        new
                        {
                            Id = 25,
                            Name = "supplier 25"
                        },
                        new
                        {
                            Id = 26,
                            Name = "supplier 26"
                        },
                        new
                        {
                            Id = 27,
                            Name = "supplier 27"
                        },
                        new
                        {
                            Id = 28,
                            Name = "supplier 28"
                        },
                        new
                        {
                            Id = 29,
                            Name = "supplier 29"
                        },
                        new
                        {
                            Id = 30,
                            Name = "supplier 30"
                        },
                        new
                        {
                            Id = 31,
                            Name = "supplier 31"
                        },
                        new
                        {
                            Id = 32,
                            Name = "supplier 32"
                        },
                        new
                        {
                            Id = 33,
                            Name = "supplier 33"
                        },
                        new
                        {
                            Id = 34,
                            Name = "supplier 34"
                        },
                        new
                        {
                            Id = 35,
                            Name = "supplier 35"
                        },
                        new
                        {
                            Id = 36,
                            Name = "supplier 36"
                        },
                        new
                        {
                            Id = 37,
                            Name = "supplier 37"
                        },
                        new
                        {
                            Id = 38,
                            Name = "supplier 38"
                        },
                        new
                        {
                            Id = 39,
                            Name = "supplier 39"
                        },
                        new
                        {
                            Id = 40,
                            Name = "supplier 40"
                        },
                        new
                        {
                            Id = 41,
                            Name = "supplier 41"
                        },
                        new
                        {
                            Id = 42,
                            Name = "supplier 42"
                        },
                        new
                        {
                            Id = 43,
                            Name = "supplier 43"
                        },
                        new
                        {
                            Id = 44,
                            Name = "supplier 44"
                        },
                        new
                        {
                            Id = 45,
                            Name = "supplier 45"
                        },
                        new
                        {
                            Id = 46,
                            Name = "supplier 46"
                        },
                        new
                        {
                            Id = 47,
                            Name = "supplier 47"
                        },
                        new
                        {
                            Id = 48,
                            Name = "supplier 48"
                        },
                        new
                        {
                            Id = 49,
                            Name = "supplier 49"
                        },
                        new
                        {
                            Id = 50,
                            Name = "supplier 50"
                        },
                        new
                        {
                            Id = 51,
                            Name = "supplier 51"
                        },
                        new
                        {
                            Id = 52,
                            Name = "supplier 52"
                        },
                        new
                        {
                            Id = 53,
                            Name = "supplier 53"
                        },
                        new
                        {
                            Id = 54,
                            Name = "supplier 54"
                        },
                        new
                        {
                            Id = 55,
                            Name = "supplier 55"
                        },
                        new
                        {
                            Id = 56,
                            Name = "supplier 56"
                        },
                        new
                        {
                            Id = 57,
                            Name = "supplier 57"
                        },
                        new
                        {
                            Id = 58,
                            Name = "supplier 58"
                        },
                        new
                        {
                            Id = 59,
                            Name = "supplier 59"
                        },
                        new
                        {
                            Id = 60,
                            Name = "supplier 60"
                        },
                        new
                        {
                            Id = 61,
                            Name = "supplier 61"
                        },
                        new
                        {
                            Id = 62,
                            Name = "supplier 62"
                        },
                        new
                        {
                            Id = 63,
                            Name = "supplier 63"
                        },
                        new
                        {
                            Id = 64,
                            Name = "supplier 64"
                        },
                        new
                        {
                            Id = 65,
                            Name = "supplier 65"
                        },
                        new
                        {
                            Id = 66,
                            Name = "supplier 66"
                        },
                        new
                        {
                            Id = 67,
                            Name = "supplier 67"
                        },
                        new
                        {
                            Id = 68,
                            Name = "supplier 68"
                        },
                        new
                        {
                            Id = 69,
                            Name = "supplier 69"
                        },
                        new
                        {
                            Id = 70,
                            Name = "supplier 70"
                        },
                        new
                        {
                            Id = 71,
                            Name = "supplier 71"
                        },
                        new
                        {
                            Id = 72,
                            Name = "supplier 72"
                        },
                        new
                        {
                            Id = 73,
                            Name = "supplier 73"
                        },
                        new
                        {
                            Id = 74,
                            Name = "supplier 74"
                        },
                        new
                        {
                            Id = 75,
                            Name = "supplier 75"
                        },
                        new
                        {
                            Id = 76,
                            Name = "supplier 76"
                        },
                        new
                        {
                            Id = 77,
                            Name = "supplier 77"
                        },
                        new
                        {
                            Id = 78,
                            Name = "supplier 78"
                        },
                        new
                        {
                            Id = 79,
                            Name = "supplier 79"
                        },
                        new
                        {
                            Id = 80,
                            Name = "supplier 80"
                        },
                        new
                        {
                            Id = 81,
                            Name = "supplier 81"
                        },
                        new
                        {
                            Id = 82,
                            Name = "supplier 82"
                        },
                        new
                        {
                            Id = 83,
                            Name = "supplier 83"
                        },
                        new
                        {
                            Id = 84,
                            Name = "supplier 84"
                        },
                        new
                        {
                            Id = 85,
                            Name = "supplier 85"
                        },
                        new
                        {
                            Id = 86,
                            Name = "supplier 86"
                        },
                        new
                        {
                            Id = 87,
                            Name = "supplier 87"
                        },
                        new
                        {
                            Id = 88,
                            Name = "supplier 88"
                        },
                        new
                        {
                            Id = 89,
                            Name = "supplier 89"
                        },
                        new
                        {
                            Id = 90,
                            Name = "supplier 90"
                        },
                        new
                        {
                            Id = 91,
                            Name = "supplier 91"
                        },
                        new
                        {
                            Id = 92,
                            Name = "supplier 92"
                        },
                        new
                        {
                            Id = 93,
                            Name = "supplier 93"
                        },
                        new
                        {
                            Id = 94,
                            Name = "supplier 94"
                        },
                        new
                        {
                            Id = 95,
                            Name = "supplier 95"
                        },
                        new
                        {
                            Id = 96,
                            Name = "supplier 96"
                        },
                        new
                        {
                            Id = 97,
                            Name = "supplier 97"
                        },
                        new
                        {
                            Id = 98,
                            Name = "supplier 98"
                        },
                        new
                        {
                            Id = 99,
                            Name = "supplier 99"
                        },
                        new
                        {
                            Id = 100,
                            Name = "supplier 100"
                        },
                        new
                        {
                            Id = 101,
                            Name = "supplier 101"
                        },
                        new
                        {
                            Id = 102,
                            Name = "supplier 102"
                        },
                        new
                        {
                            Id = 103,
                            Name = "supplier 103"
                        },
                        new
                        {
                            Id = 104,
                            Name = "supplier 104"
                        },
                        new
                        {
                            Id = 105,
                            Name = "supplier 105"
                        },
                        new
                        {
                            Id = 106,
                            Name = "supplier 106"
                        },
                        new
                        {
                            Id = 107,
                            Name = "supplier 107"
                        },
                        new
                        {
                            Id = 108,
                            Name = "supplier 108"
                        },
                        new
                        {
                            Id = 109,
                            Name = "supplier 109"
                        },
                        new
                        {
                            Id = 110,
                            Name = "supplier 110"
                        },
                        new
                        {
                            Id = 111,
                            Name = "supplier 111"
                        },
                        new
                        {
                            Id = 112,
                            Name = "supplier 112"
                        },
                        new
                        {
                            Id = 113,
                            Name = "supplier 113"
                        },
                        new
                        {
                            Id = 114,
                            Name = "supplier 114"
                        },
                        new
                        {
                            Id = 115,
                            Name = "supplier 115"
                        },
                        new
                        {
                            Id = 116,
                            Name = "supplier 116"
                        },
                        new
                        {
                            Id = 117,
                            Name = "supplier 117"
                        },
                        new
                        {
                            Id = 118,
                            Name = "supplier 118"
                        },
                        new
                        {
                            Id = 119,
                            Name = "supplier 119"
                        },
                        new
                        {
                            Id = 120,
                            Name = "supplier 120"
                        },
                        new
                        {
                            Id = 121,
                            Name = "supplier 121"
                        },
                        new
                        {
                            Id = 122,
                            Name = "supplier 122"
                        },
                        new
                        {
                            Id = 123,
                            Name = "supplier 123"
                        },
                        new
                        {
                            Id = 124,
                            Name = "supplier 124"
                        },
                        new
                        {
                            Id = 125,
                            Name = "supplier 125"
                        },
                        new
                        {
                            Id = 126,
                            Name = "supplier 126"
                        },
                        new
                        {
                            Id = 127,
                            Name = "supplier 127"
                        },
                        new
                        {
                            Id = 128,
                            Name = "supplier 128"
                        },
                        new
                        {
                            Id = 129,
                            Name = "supplier 129"
                        },
                        new
                        {
                            Id = 130,
                            Name = "supplier 130"
                        },
                        new
                        {
                            Id = 131,
                            Name = "supplier 131"
                        },
                        new
                        {
                            Id = 132,
                            Name = "supplier 132"
                        },
                        new
                        {
                            Id = 133,
                            Name = "supplier 133"
                        },
                        new
                        {
                            Id = 134,
                            Name = "supplier 134"
                        },
                        new
                        {
                            Id = 135,
                            Name = "supplier 135"
                        },
                        new
                        {
                            Id = 136,
                            Name = "supplier 136"
                        },
                        new
                        {
                            Id = 137,
                            Name = "supplier 137"
                        },
                        new
                        {
                            Id = 138,
                            Name = "supplier 138"
                        },
                        new
                        {
                            Id = 139,
                            Name = "supplier 139"
                        },
                        new
                        {
                            Id = 140,
                            Name = "supplier 140"
                        },
                        new
                        {
                            Id = 141,
                            Name = "supplier 141"
                        },
                        new
                        {
                            Id = 142,
                            Name = "supplier 142"
                        },
                        new
                        {
                            Id = 143,
                            Name = "supplier 143"
                        },
                        new
                        {
                            Id = 144,
                            Name = "supplier 144"
                        },
                        new
                        {
                            Id = 145,
                            Name = "supplier 145"
                        },
                        new
                        {
                            Id = 146,
                            Name = "supplier 146"
                        },
                        new
                        {
                            Id = 147,
                            Name = "supplier 147"
                        },
                        new
                        {
                            Id = 148,
                            Name = "supplier 148"
                        },
                        new
                        {
                            Id = 149,
                            Name = "supplier 149"
                        },
                        new
                        {
                            Id = 150,
                            Name = "supplier 150"
                        },
                        new
                        {
                            Id = 151,
                            Name = "supplier 151"
                        },
                        new
                        {
                            Id = 152,
                            Name = "supplier 152"
                        },
                        new
                        {
                            Id = 153,
                            Name = "supplier 153"
                        },
                        new
                        {
                            Id = 154,
                            Name = "supplier 154"
                        },
                        new
                        {
                            Id = 155,
                            Name = "supplier 155"
                        },
                        new
                        {
                            Id = 156,
                            Name = "supplier 156"
                        },
                        new
                        {
                            Id = 157,
                            Name = "supplier 157"
                        },
                        new
                        {
                            Id = 158,
                            Name = "supplier 158"
                        },
                        new
                        {
                            Id = 159,
                            Name = "supplier 159"
                        },
                        new
                        {
                            Id = 160,
                            Name = "supplier 160"
                        },
                        new
                        {
                            Id = 161,
                            Name = "supplier 161"
                        },
                        new
                        {
                            Id = 162,
                            Name = "supplier 162"
                        },
                        new
                        {
                            Id = 163,
                            Name = "supplier 163"
                        },
                        new
                        {
                            Id = 164,
                            Name = "supplier 164"
                        },
                        new
                        {
                            Id = 165,
                            Name = "supplier 165"
                        },
                        new
                        {
                            Id = 166,
                            Name = "supplier 166"
                        },
                        new
                        {
                            Id = 167,
                            Name = "supplier 167"
                        },
                        new
                        {
                            Id = 168,
                            Name = "supplier 168"
                        },
                        new
                        {
                            Id = 169,
                            Name = "supplier 169"
                        },
                        new
                        {
                            Id = 170,
                            Name = "supplier 170"
                        },
                        new
                        {
                            Id = 171,
                            Name = "supplier 171"
                        },
                        new
                        {
                            Id = 172,
                            Name = "supplier 172"
                        },
                        new
                        {
                            Id = 173,
                            Name = "supplier 173"
                        },
                        new
                        {
                            Id = 174,
                            Name = "supplier 174"
                        },
                        new
                        {
                            Id = 175,
                            Name = "supplier 175"
                        },
                        new
                        {
                            Id = 176,
                            Name = "supplier 176"
                        },
                        new
                        {
                            Id = 177,
                            Name = "supplier 177"
                        },
                        new
                        {
                            Id = 178,
                            Name = "supplier 178"
                        },
                        new
                        {
                            Id = 179,
                            Name = "supplier 179"
                        },
                        new
                        {
                            Id = 180,
                            Name = "supplier 180"
                        },
                        new
                        {
                            Id = 181,
                            Name = "supplier 181"
                        },
                        new
                        {
                            Id = 182,
                            Name = "supplier 182"
                        },
                        new
                        {
                            Id = 183,
                            Name = "supplier 183"
                        },
                        new
                        {
                            Id = 184,
                            Name = "supplier 184"
                        },
                        new
                        {
                            Id = 185,
                            Name = "supplier 185"
                        },
                        new
                        {
                            Id = 186,
                            Name = "supplier 186"
                        },
                        new
                        {
                            Id = 187,
                            Name = "supplier 187"
                        },
                        new
                        {
                            Id = 188,
                            Name = "supplier 188"
                        },
                        new
                        {
                            Id = 189,
                            Name = "supplier 189"
                        },
                        new
                        {
                            Id = 190,
                            Name = "supplier 190"
                        },
                        new
                        {
                            Id = 191,
                            Name = "supplier 191"
                        },
                        new
                        {
                            Id = 192,
                            Name = "supplier 192"
                        },
                        new
                        {
                            Id = 193,
                            Name = "supplier 193"
                        },
                        new
                        {
                            Id = 194,
                            Name = "supplier 194"
                        },
                        new
                        {
                            Id = 195,
                            Name = "supplier 195"
                        },
                        new
                        {
                            Id = 196,
                            Name = "supplier 196"
                        },
                        new
                        {
                            Id = 197,
                            Name = "supplier 197"
                        },
                        new
                        {
                            Id = 198,
                            Name = "supplier 198"
                        },
                        new
                        {
                            Id = 199,
                            Name = "supplier 199"
                        },
                        new
                        {
                            Id = 200,
                            Name = "supplier 200"
                        });
                });

            modelBuilder.Entity("BasicLinQ.Entities.Product", b =>
                {
                    b.HasOne("BasicLinQ.Entities.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.HasOne("BasicLinQ.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId");

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BasicLinQ.Entities.ProductCategory", b =>
                {
                    b.HasOne("BasicLinQ.Entities.Supplier", "Supplier")
                        .WithMany("ProductCategories")
                        .HasForeignKey("SupplierId");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BasicLinQ.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BasicLinQ.Entities.Supplier", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
