// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TStore.Shared.Persistence;

namespace TStore.Shared.Migrations
{
    [DbContext(typeof(TStoreContext))]
    [Migration("20220825154200_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TStore.Shared.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("Discount")
                        .HasColumnType("float");

                    b.Property<double?>("ShipAmount")
                        .HasColumnType("float");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TStore.Shared.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TStore.Shared.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c7fba07-5bdf-4412-b11f-ca9208dc9a73"),
                            Name = "Laptop",
                            Price = 1000.0
                        },
                        new
                        {
                            Id = new Guid("4cf48269-8012-4dff-8fb7-e640320c029f"),
                            Name = "Television",
                            Price = 2000.0
                        },
                        new
                        {
                            Id = new Guid("f3ef7bd9-1a93-427b-8b07-c1b9022fef91"),
                            Name = "Telephone",
                            Price = 300.0
                        },
                        new
                        {
                            Id = new Guid("4172540f-6436-4aad-948f-c051e590ac70"),
                            Name = "Iphone 14",
                            Price = 5000.0
                        },
                        new
                        {
                            Id = new Guid("162e861c-7151-4193-b379-f5a86555dafc"),
                            Name = "Samsung Galaxy",
                            Price = 2000.0
                        },
                        new
                        {
                            Id = new Guid("ad74d572-3e1f-4152-b1ea-f4381a813918"),
                            Name = "Xbox",
                            Price = 7000.0
                        });
                });

            modelBuilder.Entity("TStore.Shared.Entities.OrderItem", b =>
                {
                    b.HasOne("TStore.Shared.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TStore.Shared.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
