// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace efcore_6.DemoCompiledModel
{
    public partial class DemoCompiledDbContextModel
    {
        partial void Initialize()
        {
            var productEntity = ProductEntityEntityType.Create(this);
            var userEntity = UserEntityEntityType.Create(this);

            ProductEntityEntityType.CreateAnnotations(productEntity);
            UserEntityEntityType.CreateAnnotations(userEntity);

            AddAnnotation("ProductVersion", "6.0.28");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
