// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using efcore_demos.DataAccess;

#pragma warning disable 219, 612, 618
#nullable disable

namespace efcore_6.DemoCompiledModel
{
    [DbContext(typeof(DemoCompiledDbContext))]
    public partial class DemoCompiledDbContextModel : RuntimeModel
    {
        static DemoCompiledDbContextModel()
        {
            var model = new DemoCompiledDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static DemoCompiledDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
