// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedisSharing.UseCases.Caching.SqlServerStore;

#nullable disable

namespace RedisSharing.UseCases.Caching.Migrations
{
    [DbContext(typeof(CachingContext))]
    [Migration("20220109040633_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RedisSharing.UseCases.Caching.Models.CountryItem", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Name");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("RedisSharing.UseCases.Caching.Models.CountryState", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Name", "CountryName");

                    b.HasIndex("CountryName");

                    b.ToTable("States");
                });

            modelBuilder.Entity("RedisSharing.UseCases.Caching.Models.CountryState", b =>
                {
                    b.HasOne("RedisSharing.UseCases.Caching.Models.CountryItem", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("RedisSharing.UseCases.Caching.Models.CountryItem", b =>
                {
                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
